### ISSUE TITLE
Huge security problem, not https

### ISSUE THREAD

**Issue by Benhgift** [coinfee/coinfee-python#1]
Someone can easily man-in-the-middle attack by changing the destination address to steal the money.

This is a huge flaw. Just use https to fix it.

Pointed out by this reddit reply: https://reddit.com/r/Python/comments/5ednyo/comment/dacp51f

**Comment by teran-mckinney** [comment]
Yeah... I know.

I hate HTTPS. Well, I guess SSL. And more than SSL, the whole CA system around it. It's insecure, centralized, and probably one of the worst standards we actively use.

I want to add in an integrated checksum at some point. But for now, and either way...

https://coinfee.net/

I just set it up. There isn't even a clean way to add SSL in some sort of configuration management-happy way. Even with Letsencrypt. I'll have to keep working on that.

Will setup automatic HTTP->HTTPS at some point. Need to add this to the library, too.
